import frappe
import os
import zipfile
from io import BytesIO
from frappe.utils.file_manager import save_file
from frappe.utils.pdf import get_pdf

@frappe.whitelist()
def generate_shipment_bundle(bundle_name):
    """
    Generate a ZIP bundle of all documents related to a shipment
    """
    bundle = frappe.get_doc('Shipment Document Bundle', bundle_name)
    
    # Create a BytesIO object to store the ZIP file
    zip_buffer = BytesIO()
    
    with zipfile.ZipFile(zip_buffer, 'w', zipfile.ZIP_DEFLATED) as zip_file:
        
        # Helper function to add document to ZIP
        def add_document_to_zip(doctype, docname, folder_name):
            if not docname:
                return
            
            try:
                doc = frappe.get_doc(doctype, docname)
                
                # Add print format as PDF
                if bundle.include_print_formats:
                    try:
                        pdf_content = get_pdf(frappe.get_print(doctype, docname))
                        zip_file.writestr(f"{folder_name}/{doctype}_{docname}.pdf", pdf_content)
                    except Exception as e:
                        frappe.log_error(f"Error generating PDF for {doctype} {docname}: {str(e)}")
                
                # Add attachments
                if bundle.include_attachments:
                    attachments = frappe.get_all('File', 
                        filters={
                            'attached_to_doctype': doctype,
                            'attached_to_name': docname
                        },
                        fields=['file_url', 'file_name']
                    )
                    
                    for attachment in attachments:
                        try:
                            file_path = frappe.get_site_path('public', attachment.file_url.lstrip('/'))
                            if os.path.exists(file_path):
                                with open(file_path, 'rb') as f:
                                    zip_file.writestr(
                                        f"{folder_name}/attachments/{attachment.file_name}",
                                        f.read()
                                    )
                        except Exception as e:
                            frappe.log_error(f"Error adding attachment {attachment.file_name}: {str(e)}")
            
            except Exception as e:
                frappe.log_error(f"Error processing {doctype} {docname}: {str(e)}")
        
        # Add all linked documents
        if bundle.sales_order:
            add_document_to_zip('Sales Order', bundle.sales_order, '01_Orders')
        
        if bundle.purchase_order:
            add_document_to_zip('Purchase Order', bundle.purchase_order, '01_Orders')
        
        if bundle.commercial_invoice:
            add_document_to_zip('Sales Invoice', bundle.commercial_invoice, '02_Invoices')
        
        if bundle.delivery_note:
            add_document_to_zip('Delivery Note', bundle.delivery_note, '03_Delivery')
        
        if bundle.packing_slip:
            add_document_to_zip('Packing Slip', bundle.packing_slip, '04_Packing')
        
        if bundle.shipment:
            add_document_to_zip('Shipment', bundle.shipment, '05_Shipment')
        
        if bundle.bill_of_lading:
            add_document_to_zip('Bill of Lading', bundle.bill_of_lading, '06_Transport_Documents')
        
        if bundle.certificate_of_origin:
            add_document_to_zip('Certificate of Origin', bundle.certificate_of_origin, '07_Certificates')
        
        if bundle.letter_of_credit:
            add_document_to_zip('Letter of Credit', bundle.letter_of_credit, '08_Financial_Documents')
        
        # Add a manifest file
        manifest_content = f"""SHIPMENT DOCUMENT BUNDLE MANIFEST
=====================================

Bundle Name: {bundle.bundle_name}
Bundle Date: {bundle.bundle_date}
Generated: {frappe.utils.now()}
Generated By: {frappe.session.user}

INCLUDED DOCUMENTS:
-------------------
Sales Order: {bundle.sales_order or 'N/A'}
Purchase Order: {bundle.purchase_order or 'N/A'}
Commercial Invoice: {bundle.commercial_invoice or 'N/A'}
Delivery Note: {bundle.delivery_note or 'N/A'}
Packing Slip: {bundle.packing_slip or 'N/A'}
Shipment: {bundle.shipment or 'N/A'}
Bill of Lading: {bundle.bill_of_lading or 'N/A'}
Certificate of Origin: {bundle.certificate_of_origin or 'N/A'}
Letter of Credit: {bundle.letter_of_credit or 'N/A'}

Customs Declaration: {bundle.customs_declaration or 'N/A'}
Insurance Certificate: {bundle.insurance_certificate or 'N/A'}
Inspection Certificate: {bundle.inspection_certificate or 'N/A'}

BUNDLE OPTIONS:
---------------
Include Attachments: {'Yes' if bundle.include_attachments else 'No'}
Include Print Formats: {'Yes' if bundle.include_print_formats else 'No'}

Remarks: {bundle.remarks or 'None'}
"""
        zip_file.writestr('MANIFEST.txt', manifest_content)
    
    # Save the ZIP file
    zip_buffer.seek(0)
    file_name = f"Shipment_Bundle_{bundle.name}_{frappe.utils.now_datetime().strftime('%Y%m%d_%H%M%S')}.zip"
    
    file_doc = save_file(
        file_name,
        zip_buffer.read(),
        'Shipment Document Bundle',
        bundle.name,
        is_private=1
    )
    
    # Update the bundle document
    bundle.generated_file = file_doc.file_url
    bundle.generation_date = frappe.utils.now()
    bundle.generated_by = frappe.session.user
    bundle.status = 'Generated'
    bundle.save(ignore_permissions=True)
    frappe.db.commit()
    
    return {
        'success': True,
        'file_url': file_doc.file_url,
        'file_name': file_name,
        'message': f'Bundle generated successfully with {len(zip_buffer.getvalue())} bytes'
    }


@frappe.whitelist()
def create_bundle_from_shipment(shipment_name):
    """
    Create a document bundle automatically from a shipment
    """
    shipment = frappe.get_doc('Shipment', shipment_name)
    
    # Find related documents
    sales_order = None
    purchase_order = None
    delivery_note = None
    
    # Try to find related delivery notes
    delivery_notes = frappe.get_all('Shipment Delivery Note',
        filters={'parent': shipment_name},
        fields=['delivery_note']
    )
    if delivery_notes:
        delivery_note = delivery_notes[0].delivery_note
        
        # Get sales order from delivery note
        dn = frappe.get_doc('Delivery Note', delivery_note)
        if dn.items and dn.items[0].against_sales_order:
            sales_order = dn.items[0].against_sales_order
    
    # Find related Bill of Lading
    bill_of_lading = frappe.db.get_value('Bill of Lading',
        {'shipment': shipment_name},
        'name'
    )
    
    # Find related Certificate of Origin
    certificate_of_origin = frappe.db.get_value('Certificate of Origin',
        {'shipment': shipment_name},
        'name'
    )
    
    # Create bundle
    bundle = frappe.get_doc({
        'doctype': 'Shipment Document Bundle',
        'bundle_name': f'Bundle for {shipment_name}',
        'shipment': shipment_name,
        'sales_order': sales_order,
        'delivery_note': delivery_note,
        'bill_of_lading': bill_of_lading,
        'certificate_of_origin': certificate_of_origin,
        'bundle_type': 'Export',
        'include_attachments': 1,
        'include_print_formats': 1
    })
    bundle.insert(ignore_permissions=True)
    frappe.db.commit()
    
    return bundle.name
